import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const profileUrl = new URL("../src/content/anthony-profile.md", import.meta.url);
const outputUrl = new URL("../convex/anthonyProfile.generated.ts", import.meta.url);
const profile = readFileSync(fileURLToPath(profileUrl), "utf8");
const version = createHash("sha256").update(profile).digest("hex").slice(0, 16);
const escapedProfile = profile
  .replaceAll("\\", "\\\\")
  .replaceAll("`", "\\`")
  .replaceAll("${", "\\${");

writeFileSync(
  fileURLToPath(outputUrl),
  `// Generated by bun run assistant:sync-profile. Do not edit.\nexport const ANTHONY_PROFILE_VERSION = "${version}";\nexport const ANTHONY_PROFILE = \`${escapedProfile}\`;\n`,
);
