/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as ApiAssistantCandidateRouteImport } from './app/api.assistant.candidate'
import { Route as ApiAssistantFaqsRouteImport } from './app/api.assistant.faqs'
import { Route as ApiAssistantTurnRouteImport } from './app/api.assistant.turn'
import { Route as ApiRealtimeSessionRouteImport } from './app/api.realtime.session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantCandidateRoute = ApiAssistantCandidateRouteImport.update({
  id: '/api/assistant/candidate',
  path: '/api/assistant/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantFaqsRoute = ApiAssistantFaqsRouteImport.update({
  id: '/api/assistant/faqs',
  path: '/api/assistant/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantTurnRoute = ApiAssistantTurnRouteImport.update({
  id: '/api/assistant/turn',
  path: '/api/assistant/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeSessionRoute = ApiRealtimeSessionRouteImport.update({
  id: '/api/realtime/session',
  path: '/api/realtime/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/assistant/candidate': typeof ApiAssistantCandidateRoute
  '/api/assistant/faqs': typeof ApiAssistantFaqsRoute
  '/api/assistant/turn': typeof ApiAssistantTurnRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assistant/candidate': typeof ApiAssistantCandidateRoute
  '/api/assistant/faqs': typeof ApiAssistantFaqsRoute
  '/api/assistant/turn': typeof ApiAssistantTurnRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/assistant/candidate': typeof ApiAssistantCandidateRoute
  '/api/assistant/faqs': typeof ApiAssistantFaqsRoute
  '/api/assistant/turn': typeof ApiAssistantTurnRoute
  '/api/realtime/session': typeof ApiRealtimeSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/assistant/candidate'
    | '/api/assistant/faqs'
    | '/api/assistant/turn'
    | '/api/realtime/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assistant/candidate'
    | '/api/assistant/faqs'
    | '/api/assistant/turn'
    | '/api/realtime/session'
  id:
    | '__root__'
    | '/'
    | '/api/assistant/candidate'
    | '/api/assistant/faqs'
    | '/api/assistant/turn'
    | '/api/realtime/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAssistantCandidateRoute: typeof ApiAssistantCandidateRoute
  ApiAssistantFaqsRoute: typeof ApiAssistantFaqsRoute
  ApiAssistantTurnRoute: typeof ApiAssistantTurnRoute
  ApiRealtimeSessionRoute: typeof ApiRealtimeSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/candidate': {
      id: '/api/assistant/candidate'
      path: '/api/assistant/candidate'
      fullPath: '/api/assistant/candidate'
      preLoaderRoute: typeof ApiAssistantCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/faqs': {
      id: '/api/assistant/faqs'
      path: '/api/assistant/faqs'
      fullPath: '/api/assistant/faqs'
      preLoaderRoute: typeof ApiAssistantFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/turn': {
      id: '/api/assistant/turn'
      path: '/api/assistant/turn'
      fullPath: '/api/assistant/turn'
      preLoaderRoute: typeof ApiAssistantTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime/session': {
      id: '/api/realtime/session'
      path: '/api/realtime/session'
      fullPath: '/api/realtime/session'
      preLoaderRoute: typeof ApiRealtimeSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAssistantCandidateRoute: ApiAssistantCandidateRoute,
  ApiAssistantFaqsRoute: ApiAssistantFaqsRoute,
  ApiAssistantTurnRoute: ApiAssistantTurnRoute,
  ApiRealtimeSessionRoute: ApiRealtimeSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
